Bot/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import CompanyStructureUpdateView, CompanyStructureView, CompanyInfoUpdateView, CompanyInfoView, DeleteComplaintView, ComplaintView, OfferView, DeleteOfferView, DeleteAdminsView, AdminsView, search, HomeView, DeleteAdvanceView, EmployeeView, AddEmployeeView, UpdateEmployeeView, DeleteEmployeeView, TaskView, DeleteTaskView, TaskDetailView, AddTaskView, TaskUpdateView, AdvanceView, login_view, logout_view , register_view
app_name = 'main'

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path("company_info/", CompanyInfoView.as_view(), name='company_info'),
    path("company_structure/", CompanyStructureView.as_view(), name='company_structure'),
    path("employee/", EmployeeView.as_view(), name='employee'),
    path("add_employee/", AddEmployeeView.as_view(), name='add_employee'),  
    path("delete_employee/<int:pk>/delete", DeleteEmployeeView.as_view(), name='delete_employee'),
    path("task/", TaskView.as_view(), name='task'),
    path('delete_task/<int:pk>/delete', DeleteTaskView.as_view(), name='delete_task'),
    path('task/<int:task_id>/', TaskDetailView.as_view(), name='task'),
    path("add_task/", AddTaskView.as_view(), name='add_task'),
    path('update_task/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
    path('update_employee/<int:pk>/', UpdateEmployeeView.as_view(), name='update_employee'),
    path('company_info/update/<int:pk>/', CompanyInfoUpdateView.as_view(), name='update_company_info'),
    path('update_company_structure/update/<int:pk>/', CompanyStructureUpdateView.as_view(), name='update_company_structure'),
    path("advance/", AdvanceView.as_view(), name='advance'),
    path("complaint/", ComplaintView.as_view(), name='complaint'),
    path("offer/", OfferView.as_view(), name='offer'),
    path('delete_advance/<int:pk>/delete', DeleteAdvanceView.as_view(), name='delete_advance'),
    path('delete_offer/<int:pk>/delete', DeleteOfferView.as_view(), name='delete_offer'),
    path('delete_admins/<int:pk>/delete', DeleteAdminsView.as_view(), name='delete_admins'),
    path('delete_complaint/<int:pk>/delete', DeleteComplaintView.as_view(), name='delete_complaint'),
    path('admins/', AdminsView.as_view(), name='admins'),
    path("search/", search, name='search'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view , name='register'),
]

app/models.py
from django.db import models
from django.core import validators
    
class TelegramUser(models.Model):
    full_name = models.CharField(max_length=40, null=True, blank=True)
    telegram_id =  models.CharField(max_length=10, verbose_name='Telegram_ID')
    add_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.telegram_id

class Employee(models.Model):
    positions = (
        ('admin',"Admin"),
        ('manager', "Manager"),
        ('worker', "Ishchi"),
        ('student', "Shogird"),   
    )
    status = models.BooleanField(default=False)
    position = models.CharField(max_length=55, default='worker', choices=positions, verbose_name='Enter the position', help_text="Choose positions")
    full_name = models.CharField(max_length=155, verbose_name='Enter the name')
    phone_number = models.CharField(max_length=13, verbose_name='Enter the phone number')
    telegram_id = models.ForeignKey(TelegramUser, on_delete=models.CASCADE, related_name='employees')
    image = models.ImageField(upload_to='images/', blank=True, validators=[
        validators.FileExtensionValidator(allowed_extensions=['ico','png','jpeg','jpg'], 
            message="Enter an image in the format below('ico','png','jpeg','jpg')")
        ])
    add_date = models.DateTimeField(auto_now_add=True)
       
    def get_employee_attendance_display(self):
        return "Kelgan" if self.status else "Kelmagan"
    
    def __str__(self):
        return f"{self.telegram_id} - {self.full_name}"

class Task(models.Model):
    STATUS_CHOICES = (
        ('active',"Aktiv"),
        ('progress', "Jarayonda"),
        ('done', "Bajarildi"), 
    )
    task_status = models.CharField(max_length=15, default='active', choices=STATUS_CHOICES, verbose_name='Enter the status', help_text="Choose status")
    name = models.TextField(verbose_name="Enter the task !")
    employees = models.ManyToManyField(Employee, blank=True, related_name='tasks_assigned')
    accepted = models.ManyToManyField(Employee, blank=True, related_name='tasks_accepted')
    image = models.ImageField(upload_to='images/', blank=True, validators=[
        validators.FileExtensionValidator(allowed_extensions=['ico','png','jpeg','jpg'], 
            message="Enter an image in the format below('ico','png','jpeg','jpg')")
        ])
    add_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.name
    
class Advance(models.Model):
    desc = models.TextField(verbose_name="Enter the task !", blank=True)
    amount = models.IntegerField(verbose_name="Amount")
    employees = models.ForeignKey(Employee, on_delete=models.CASCADE)
    add_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.desc

class CompanyInfo(models.Model):
    text = models.CharField(max_length=955, null=True, blank="True")
    video = models.FileField(upload_to="videoes", blank=True)
    image = models.ImageField(upload_to='images/', blank=True, validators=[
        validators.FileExtensionValidator(allowed_extensions=['ico','png','jpeg','jpg'], 
            message="Enter an image in the format below('ico','png','jpeg','jpg')")
        ])
    add_date = models.DateTimeField(auto_now_add=True)

class CompanyStructure(models.Model):
    text = models.CharField(max_length=255, null=True, blank="True")
    video = models.FileField(upload_to="videoes", blank=True)
    image = models.ImageField(upload_to='images/', blank=True, validators=[
        validators.FileExtensionValidator(allowed_extensions=['ico','png','jpeg','jpg'], 
            message="Enter an image in the format below('ico','png','jpeg','jpg')")
        ])
    add_date = models.DateTimeField(auto_now_add=True)

class Offer(models.Model):
    desc = models.TextField(verbose_name="Enter the task !", blank=True)
    employees = models.ForeignKey(Employee, on_delete=models.CASCADE)
    add_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.desc
    
class Complaint(models.Model):
    desc = models.TextField(verbose_name="Enter the task !", blank=True)
    employees = models.ForeignKey(Employee, on_delete=models.CASCADE)
    add_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.desc

templates/add_employee.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}

<div class="heading-elements hidden-mobile" style="margin-left: 10px;">
    <a href="{% url 'main:employee' %}" id="addEmployeeLink">
        <button class="btn btn-primary btn-icon-fixed" style="margin-top: 10px;"><span class="icon-indent-increase"></span> Xodimlar ro'yxati </button>
    </a>
</div>
                    
<!-- START PAGE CONTAINER -->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Xodim qo'shish</h2>
            <form action="{% url 'main:add_employee' %}" method="post">

                {% csrf_token %}
                <div class="block block-condensed padding-20">
                    <div class="form-group">
                        <label for="telegram_id"><span class="fa fa-send-o"></span> Telegram_id kiriting:</label>
                        <select name="telegram_id" id="telegram_id" class="form-control">
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.telegram_id }} - {{ user.full_name }} </option>
                            {% endfor %}
                        </select>
                    </div>
                                        
                    <div class="form-group">
                        <label for="full_name"><span class="icon-user"></span> To'liq ismini kiriting :</label>
                        <input type="text" class="form-control" id="full_name" name="full_name" placeholder="To'liq ismi">
                    </div>
                    
                    <div class="form-group">
                        <label for="position"><span class="icon-briefcase"></span> Lavozimni tanlang:</label>
                        <select name="position" id="position" class="form-control">
                        {% for choice in form.position.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                        </select>
                    </div>
                                        
                    <div class="form-group">
                        <label for="phone_number"><span class="icon-smartphone"></span> Telefon raqami:</label>
                        <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Telefon raqami">
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Saqlash</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END PAGE CONTAINER -->
{% endblock %}

templates/admins.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
                    <!-- END PAGE HEADING -->
                    <div class="heading-elements hidden-mobile" style="margin-left: 10px;">
                        <a href="{% url 'main:register' %}" id="addEmployeeLink">
                            <button class="btn btn-primary btn-icon-fixed" style="margin-top: 10px;"><span class="fa fa-user-plus"></span> Ro'yxatdan o'tish </button>
                        </a>
                    </div>
                    <!-- START PAGE CONTAINER -->
                    <div class="container">
                        <div class="row">
                            {% for e in user %}
                            <div class="col-md-4 col-xs-6">                                
                                <div class="block block-condensed padding-top-5">
                                    <div class="list-group">                                        
                                        <div class="list-group-item"><span class="fa fa-user"></span> {{ e.username }}</div>                                                                                                                                                         
                                        <div class="list-group-item"><span class="fa fa-circle"></span> ID: {{ e.id }}</div>                                                                                                                                                         
                                    </div>     
                                    <div class="list-group">
                                        <div class="block-content padding-20">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <a href="{% url 'main:delete_admins' e.id %}" class="btn btn-danger btn-clean btn-block btn-xs"><span class="fa fa-trash-o"></span> O'chirish</a>
                                                </div>                                                    
                                            </div>                                        
                                        </div>                                                                                                                                                            
                                    </div>                                     
                                </div>                                
                            </div>
                            {% endfor %}
                        </div>                        
                    </div>
                    <!-- END PAGE CONTAINER -->
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            
            <!-- APP OVERLAY -->
            <div class="app-overlay"></div>
            <!-- END APP OVERLAY -->
        </div>        
        <!-- END APP WRAPPER -->                
        {% endblock %}

templates/advance.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
                    
                    <!-- START PAGE HEADING -->
                    <div class="app-heading app-heading-bordered app-heading-page">                        
                        <div class="title">
                            <h1>Avanslar ro'yxati</h1>
                            <p>Botga a'zo bo'lgan xodimlar avans olish uchun xabarlari</p>
                        </div>               
                    </div>
                    <!-- END PAGE HEADING -->
                    
                    <!-- START PAGE CONTAINER -->
                    <div class="container">
                        <div class="row">
                            {% for a in advance %}
                            <div class="col-md-6 col-xs-6">                                
                                <div class="block block-condensed padding-top-5">    
                                    <div class="list-group">
                                        <div class="list-group-item"><span class="fa fa-user"></span> Xodim : {{ a.employees.full_name }}</div>                                          
                                        <div class="list-group-item"><span class="fa fa-suitcase"></span> Lavozimi : {{ a.employees.get_position_display }}</div>
                                        <div class="list-group-item"><span class="fa fa-paper-plane-o"></span> Telegram_id : {{ a.employees.telegram_id }}</div>
                                        <div class="list-group-item"><span class="fa fa-dollar"></span> Avans miqdori : {{ a.amount }} so'm</div>
                                        <div class="list-group-item"><span class="fa fa-commenting-o"></span> Sababi : {{ a.desc }}</div>                                                                                                                                                                
                                        <div class="list-group-item"><span class="fa fa-clock-o"></span> Vaqti : {{ a.employees.add_date|date:"H:i, F j, Y" }}</div>   
                                        <div class="list-group-item">
                                            <div class="block-content padding-top-5">
                                                <div class="row">
                                                    <div class="col-md-4 ">
                                                        <a href="{% url 'main:delete_advance' a.id %}" class="btn btn-danger btn-clean btn-block btn-xs"><span class="fa fa-trash-o"></span> O'chirish</a>
                                                    </div>                                                    
                                                </div>                                        
                                            </div> 
                                        </div>                                                                                                                                           
                                    </div>    
                                </div>                                
                            </div>
                            {% endfor %}
                        </div>                        
                    </div>
                    
                    <!-- END PAGE CONTAINER -->
                    
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            
            <!-- APP OVERLAY -->
            <div class="app-overlay"></div>
            <!-- END APP OVERLAY -->
        </div>  
        <style>
            .btn-custom {
                background-color: #000;
                color: #fff;
            }
        </style>          
        <!-- END APP WRAPPER -->                
        {% endblock %}

templates/employee.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
                    
                    <!-- START PAGE HEADING -->
                    <!-- END PAGE HEADING -->
                    <div class="heading-elements hidden-mobile" style="margin-left: 10px;">
                        <a href="{% url 'main:add_employee' %}" id="addEmployeeLink">
                            <button class="btn btn-primary btn-icon-fixed" style="margin-top: 10px;"><span class="fa fa-user-plus"></span> Xodim qo'shish </button>
                        </a>
                    </div>
                    <!-- START PAGE CONTAINER -->
                    <div class="container">
                        <div class="row">
                            {% for e in employees %}
                            <div class="col-md-4 col-xs-6">                                
                                <div class="block block-condensed padding-top-5">
                                    <div class="list-group">                                        
                                        <div class="list-group-item"><span class="fa fa-user"></span> Xodim: {{ e.full_name }}</div>                                                                                                                                                         
                                    </div>     
                                    <div class="list-group">                                        
                                        <div class="list-group-item"><span class="fa fa-suitcase"></span> Lavozimi: {{ e.get_position_display }}</div>
                                        <div class="list-group-item"><span class="fa fa-phone"></span> Telefon raqami: {{ e.phone_number }}</div>  
                                        <div class="list-group-item"><span class="fa fa-star-half-empty"></span> Holati: {{ e.get_employee_attendance_display }}</div>  
                                        <div class="list-group-item"><span class="fa fa-send"></span> Telegram ID: {{ e.telegram_id }}</a></div>

                                        <div class="block-content padding-20">
                                            <div class="row">
                                                <div class="col-md-6"> 
                                                    <a href="{% url 'main:update_employee' e.id %}" class="btn btn-info btn-clean btn-block btn-xs"><span class="fa fa-pencil"></span> Taxrirlash</a>
                                                </div>
                                                <div class="col-md-6">
                                                    <a href="{% url 'main:delete_employee' e.id %}" class="btn btn-danger btn-clean btn-block btn-xs"><span class="fa fa-trash-o"></span> O'chirish</a>
                                                </div>                                                    
                                            </div>                                        
                                        </div>                                                                                                                                                             
                                    </div>                                     
                                </div>                                
                            </div>
                            {% endfor %}
                        </div>                        
                    </div>
                    <!-- END PAGE CONTAINER -->
                </div>
                <!-- END APP CONTENT -->
                                
            </div>
            
            <!-- APP OVERLAY -->
            <div class="app-overlay"></div>
            <!-- END APP OVERLAY -->
        </div>        
        <!-- END APP WRAPPER -->                
        {% endblock %}

templates/index.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
                    <!-- END APP HEADER  -->
                    
                    <!-- START PAGE HEADING -->
                    <div class="app-heading app-heading-bordered app-heading-page">
                        <div class="icon icon-lg">
                            <span class="icon-laptop-phone"></span>
                        </div>
                        <div class="title">
                            <h1>Bosh sahifa</h1>
                            <p>Manager panel</p>
                        </div>               
                    <div class="container">
                                                
                        <div class="row">
                            <div class="col-md-4">    
                                <div class="app-widget-tile app-widget-highlight">
                                    <div class="line">
                                        <div class="subtitle"><span class="fa fa-users"></span> Jami xodimlar : {{ employees }} ta</div>
                                    </div>
                                    <br><br>
                                    <div class="line">
                                        <div class="title text-center">
                                            <span class="label label-success label-ghost label-bordered">Bugun {{ all_employee }} ta qo'shildi <span class="fa fa-check-square-o"></span></span>
                                        </div>
                                    </div>
                                    <br><br>
                                    <button type="button" class="btn btn-secondary btn-xs"><a href="{% url "main:employee" %}">Xodimlar ro'yxati</button>
                                </div>                                                                        
                            </div>
                            <div class="col-md-4">      
                                <div class="app-widget-tile app-widget-highlight">
                                    <div class="line">
                                        <div class="subtitle"><span class="fa fa-list"></span> Jami topshiriqlar : {{ tasks }} ta</div>
                                    </div>
                                    <br><br>
                                    <div class="line">
                                        <div class="title text-center">
                                            <span class="label label-warning label-ghost label-bordered">Bugun {{ all_tasks }} ta qo'shildi <span class="fa fa-check-square-o"></span></span>
                                        </div>
                                    </div>
                                    <br><br>                                  
                                    <button type="button" class="btn btn-secondary btn-xs"><a href="{% url 'main:task' %}">Topshiriqlar ro'yxati</a></button>
                                </div>                                   
                            </div>
                            <div class="col-md-4">      
                                <div class="app-widget-tile app-widget-highlight">
                                    <div class="line">
                                        <div class="subtitle"><span class="fa fa-money"></span> Jami avanslar : {{ advances }} ta</div>
                                    </div>
                                    <br><br>
                                    <div class="line">
                                        <div class="title text-center">
                                            <span class="label label-warning label-ghost label-bordered">Bugun {{ all_advances }} ta qo'shildi <span class="fa fa-check-square-o"></span></span>
                                        </div>
                                    </div>
                                    <br><br>                                     
                                    <button type="button" class="btn btn-secondary btn-xs"><a href="{% url 'main:advance' %}">Avanslar ro'yxati</a></button>
                                </div>                                 
                            </div>
                        </div>
                          
                        <div class="row">
                            <div class="col-md-12">                        
                                <!-- START LATEST TRANSACTIONS -->                     
                                <div class="block block-condensed">
                                    <div class="app-heading">                                        
                                        <div class="title">
                                            <h2>Bugungi Topshiriqlar</h2>
                                        </div>              
                                    </div>
                                    <div class="block-content">
                                        <div class="table-responsive">
                                            <table class="table table-clean-paddings margin-bottom-0">
                                                <thead>
                                                    <tr>
                                                        <th>Xodimlar</th>
                                                        <th>Topshiriqlar</th>
                                                        <th>Holati</th>
                                                        <th>Vaqti</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for task in today_tasks %}
                                                    <tr>
                                                        <td>
                                                            {% for employee in task.employees.all %}
                                                                {{ employee.full_name }}</a>,
                                                            {% endfor %}      
                                                        </td>
                                                        <td><h6><a href="{% url 'main:task' task.id %}">{{ task.name }}</a></h6></td>
                                                        <td><h6>{{ task.get_task_status_display }}</h6></td>
                                                        <td><h6>{{ task.add_date|date:"H:i"}}</h6></td>
                                                    </tr>
                                                    {% endfor %}                                                                                       
                                                </tbody>     
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                                <!-- END LATEST TRANSACTIONS -->
                            </div>
                        </div>
                        
                    </div>
                    <!-- END PAGE CONTAINER -->                 
                </div>
                <!-- END APP CONTENT -->                               
            </div>
            <!-- END APP CONTAINER -->
            <!-- APP OVERLAY -->
            <div class="app-overlay"></div>
            <!-- END APP OVERLAY -->
        </div>        
        <!-- END APP WRAPPER -->                
{% endblock %}

templates/update_employee.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
                    
<div class="heading-elements hidden-mobile" style="margin-left: 10px;">
    <a href="{% url 'main:employee' %}" id="addEmployeeLink">
        <button class="btn btn-twitter btn-icon-fixed"><span class="fa fa-list-alt"></span> Xodimlar ro'yxati </button>
    </a>
</div>

<!-- START PAGE CONTAINER -->
<div class="container">
    <div class="row">
        <div class="col-md-10 col-xs-6">                                
            <div class="block block-condensed padding-top-20">     
                <div class="list-group">                                        
                    <!-- Update Employee Form -->
                    <form method="post" action="{% url 'main:update_employee' employee.pk %}" class="block-content padding-20">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success"><span class="fa fa-download"></span> Saqlash</button>
                    </form>
                    <!-- End Update Employee Form -->
                </div>                                                                                                                                                             
            </div>                                
        </div>
    </div>                        
</div>

<!-- END PAGE CONTAINER -->
               
{% endblock %}